Repository cmsc22000-project-2018/support-tools, pull requests merged in 2018-05, with the labels that each got.

#67 Mr/help function
  consolidated_shell/testables.c
  organized_dir/func_expl.txt
  organized_dir/src/features.c
  organized_dir/src/help_func.c
Labels: actual:long

#69 added welcome message and indentation
  organized_dir/include/features.h
  organized_dir/src/features.c
  organized_dir/src/main.c
Labels: actual:short

#72 Updated Readme
  README.md
Labels: actual:medium

#73 Maxine/updated funcs
  organized_dir/Makefile
  organized_dir/func_expl.txt
  organized_dir/include/features.h
  organized_dir/include/viz_functions.h
  organized_dir/src/features.c
  organized_dir/src/main.c
  organized_dir/src/viz_functions.c
  organized_dir/src/viz_main.c
Labels: actual:medium
